### ISSUE TITLE
🇨🇭 Swiss counts

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios_data#32] opened 2020-03-23 16:31 UTC
Swiss case counts are currently not updating properly. They have updated files for individual cantons, by the aggregated file fell into disrepair. I made an issue and they'll hopefully have it fixed soon:

https://github.com/openZH/covid_19/issues/99

otherwise, we have to adjust our parser to use the individual cantonal files.

**Comment by nnoll** [comment] 2020-03-23 16:59
OK, should we make the change now or give a day or so to see if the problem is resolved?

**Comment by nnoll** [comment] 2020-03-24 21:39
I'll close this as it was fixed with your recent pull request.

**Closed as completed by nnoll** 2020-03-24 21:39 UTC
